<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hubert Producciones</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="shortcut icon" href="./assets/logo.svg" />
  </head>

  <body>
    <nav
      class="navbar navbar-expand navbar-small d-none d-sm-block CabeceraMenu"
    >
      <div class="container">
        <ul class="navbar-nav mr-auto lineasa-blancas">
          <li class="nav-item">
            <a class="nav-link"
              ><i class="material-icons">phone</i> (8) 7 40 6392</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link"
              ><i class="material-icons">mail</i> rectoria@inemtunja.edu.co</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://inemtunja.edu.co/contacto"
              ><i class="material-icons">contact_support</i> Contacto</a
            >
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link">Síguenos</a>
          </li>
          <li class="nav-item">
            <a
              class="navbar-brand"
              href="https://www.facebook.com/INEMTunjaOficial/"
              target="_blank"
              ><img
                src="https://inemtunja.edu.co/img/Faceb_White_30x30.png"
                width="30"
                height="30"
                alt=""
            /></a>
          </li>
          <li class="nav-item">
            <a
              class="navbar-brand"
              href="https://www.instagram.com/inemvirtualradio2016/?hl=es-la"
              target="_blank"
              ><img
                src="https://inemtunja.edu.co/img/Insta_White_30x30.png"
                width="30"
                height="30"
                alt=""
            /></a>
          </li>
        </ul>
      </div>
    </nav>
    <header class="Cabecera">
      <div class="ContenedorCabecera">
        <a href="#"
          ><img src="./images/logo.svg" alt="Logo" class="imagenCabecera1""/></a
        >
        <div class="Textos">
          <h1 class="TituloPrincipal">BANCO DE PROYECTOS</h1>
          <p class="ContenedoPrincipal">INEM TUNJA</p>
        </div>
        <a href="#"
          ><img src="./images/logo2.png" alt="Logo" class="imagenCabecera2"
        /></a>
      </div>

      <nav class="navbar navbar-expand navbar-dark bg-primary">
        <ul class="nav navbar-nav mx-auto menudesplegable">
          <li><a href="">COMUNICACIÓN</a></li>
          <li>
            <a href="">SALUD</a>
            <ul>
              <li><a href="">2023</a></li>
              <li><a href="">2024</a></li>
              <li><a href="">2025</a></li>
              <li>
                <a href="">2026</a>
                <ul>
                  <li><a href="">Submenu1</a></li>
                  <li><a href="">Submenu2</a></li>
                  <li><a href="">Submenu3</a></li>
                  <li><a href="">Submenu4</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li>
            <a href="">Acerca de PRUEBAS</a>
            <ul>
              <li><a href="">Submenu1</a></li>
              <li><a href="">Submenu2</a></li>
              <li><a href="">Submenu3</a></li>
              <li><a href="">Submenu4</a></li>
            </ul>
          </li>
          <li><a href="">Contacto</a></li>
        </ul>
      </nav>
    </header>

    <main class="main">
      <div class="container">
        <div style="height: 300px;"></div>
      </div>
    </main>

    <footer class="bg-rojo">
      <div class="container">
        <div class="row" style="padding-top: 1rem">
          <div class="col-md-3">
            <h4 class="text-center blanco">Nosotros</h4>
            <a
              href="https://inemtunja.edu.co/nosotros"
              style="text-decoration: none"
              ><p class="text-center blanco">Conócenos</p></a
            >
            <a
              href="https://inemtunja.edu.co/privacidad.php"
              style="text-decoration: none"
              ><p class="text-center blanco">Privacidad</p></a
            >
            <a
              href="https://inemtunja.edu.co/nosotros.php"
              style="text-decoration: none"
              ><p class="text-center blanco">Términos y Condiciones</p></a
            >
          </div>
          <div class="col-md-3">
            <h4 class="text-center blanco">Contacto</h4>
            <p class="text-center blanco">
              Carrera 15 # 9a - 72 Barrio Paraíso
            </p>
            <p class="text-center blanco">(8) 7 40 6392</p>
            <p class="text-center blanco">rectoria@inemtunja.edu.co</p>
          </div>
          <div class="col-md-3">
            <h4 class="text-center blanco">Síguenos</h4>
            <div class="row justify-content-center">
              <div class="col-md-2">
                <a
                  class="navbar-brand"
                  style="display: block; text-align: center"
                  href="https://www.facebook.com/INEMTunjaOficial/"
                  target="_blank"
                  ><img
                    src="https://inemtunja.edu.co/img/Faceb_White_30x30.png"
                    width="30"
                    height="30"
                    alt=""
                /></a>
              </div>
              <div class="col-md-2">
                <a
                  class="navbar-brand"
                  style="display: block; text-align: center"
                  href="https://www.instagram.com/inemvirtualradio2016/?hl=es-la"
                  target="_blank"
                  ><img
                    src="https://inemtunja.edu.co/img/Insta_White_30x30.png"
                    width="30"
                    height="30"
                    alt=""
                /></a>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <p class="text-center blanco">Todos los Derechos Reservados 2024</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>
